/**
 * format-output command
 * Generate markdown report from review results
 */

import type {
  FormatOutputOutput,
  ConsensusIssue,
  DebateIssue,
  Severity,
} from '../types/index.js';
import { FormatOutputInputSchema } from '../types/index.js';

const SEVERITY_ORDER: Severity[] = ['critical', 'warning', 'suggestion', 'nitpick'];

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  warning: '🟡',
  suggestion: '🔵',
  nitpick: '⚪',
};

export function formatOutput(inputJson: string): string {
  try {
    const input = JSON.parse(inputJson) as unknown;
    const validated = FormatOutputInputSchema.parse(input);

    const consensusIssues = (validated.consensusIssues || []) as ConsensusIssue[];
    const debateIssues = (validated.debateIssues || []) as DebateIssue[];
    const debateResults = (validated.debateResults || []) as any[];

    const lines: string[] = [];

    // Header
    lines.push('# Code Review Report\n');

    // Summary stats
    const bySeverity: Record<Severity, number> = {
      critical: 0,
      warning: 0,
      suggestion: 0,
      nitpick: 0,
    };

    for (const issue of consensusIssues) {
      bySeverity[issue.agreedSeverity]++;
    }

    for (const issue of debateResults) {
      if (issue.finalSeverity) {
        bySeverity[issue.finalSeverity as Severity]++;
      }
    }

    const totalIssues = Object.values(bySeverity).reduce((a, b) => a + b, 0);

    lines.push('## Summary\n');
    lines.push(`- **Total Issues:** ${totalIssues}`);
    lines.push(`- **Consensus Issues:** ${consensusIssues.length}`);
    lines.push(`- **Debated Issues:** ${debateResults.length}`);
    lines.push('');

    lines.push('### By Severity\n');
    for (const severity of SEVERITY_ORDER) {
      const count = bySeverity[severity];
      if (count > 0) {
        lines.push(
          `- ${SEVERITY_EMOJI[severity]} **${severity.toUpperCase()}:** ${count}`
        );
      }
    }
    lines.push('');

    // Consensus Issues
    if (consensusIssues.length > 0) {
      lines.push('## Consensus Issues\n');
      lines.push('_Issues with strong agreement among reviewers_\n');

      for (const severity of SEVERITY_ORDER) {
        const issuesOfSeverity = consensusIssues.filter(
          (i) => i.agreedSeverity === severity
        );

        if (issuesOfSeverity.length === 0) continue;

        lines.push(`### ${SEVERITY_EMOJI[severity]} ${severity.toUpperCase()}\n`);

        for (const issue of issuesOfSeverity) {
          lines.push(
            `**${issue.issueGroup.file}:${issue.issueGroup.line}** - ${issue.issueGroup.title}`
          );
          lines.push(
            `- Confidence: ${(issue.confidence * 100).toFixed(0)}%` +
              ` (${issue.voters.length} reviewers)`
          );

          if (issue.suggestions && issue.suggestions.length > 0) {
            lines.push('- Suggestions:');
            for (const suggestion of issue.suggestions) {
              lines.push(`  - ${suggestion}`);
            }
          }

          lines.push('');
        }
      }
    }

    // Debate Results
    if (debateResults.length > 0) {
      lines.push('## Debated Issues\n');
      lines.push('_Issues resolved through multi-round debate_\n');

      for (const result of debateResults) {
        const severity = result.finalSeverity as Severity;
        lines.push(
          `### ${SEVERITY_EMOJI[severity]} ${result.issueGroup.file}:${result.issueGroup.line} - ${result.issueGroup.title}\n`
        );
        lines.push(`**Final Severity:** ${severity.toUpperCase()}`);
        lines.push(`**Rounds:** ${result.rounds || 0}`);
        lines.push('');

        if (result.finalReasoning) {
          lines.push('**Final Reasoning:**');
          lines.push(result.finalReasoning);
          lines.push('');
        }
      }
    }

    // Unresolved Debates
    if (debateIssues.length > debateResults.length) {
      const unresolvedCount = debateIssues.length - debateResults.length;
      lines.push('## Unresolved Issues\n');
      lines.push(`${unresolvedCount} issue(s) require further discussion.\n`);
    }

    // Footer
    lines.push('---');
    lines.push('_Generated by CodeAgora Multi-Agent Review System_');

    const markdown = lines.join('\n');

    const output: FormatOutputOutput = {
      markdown,
      summary: {
        totalIssues,
        bySeverity,
        debatesHeld: debateResults.length,
      },
    };

    return JSON.stringify(output, null, 2);
  } catch (error) {
    return JSON.stringify(
      {
        error: error instanceof Error ? error.message : String(error),
      },
      null,
      2
    );
  }
}
